name: Build Web Page

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 8,20 * * *' # Runs at 8:00 and 20:00 UTC
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read       # For checkout
      pages: write        # For Pages deployment
      id-token: write     # For authentication

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python script2.py

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./ # Uploads index.html from root

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
